name: Python CI

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if you have a requirements file

    - name:  Run db scipt
      run:  python db.py

    - name: Run unit tests
      run: python -m unittest discover -s tests  # Explicitly specify the tests directory