name: Flask Python API Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Adjust this according to your project setup

    - name: Build
      run: |
        # Add any build steps here if necessary

    - name: Run Unit Tests
      run: |
        python -m unittest discover tests # Adjust this according to your test structure
